### ISSUE TITLE
Application won't start with .config file missing

### ISSUE THREAD

**Issue by fireattack** [SanderSade/DirLister#3]
I normally delete .config file to reset settings to default, and realize that the application won't start at all if you deleted .config file.

**Comment by SanderSade** [comment]
This is the default behavior of all .NET apps using app.config functionality.

The default and application-level settings are in that DirLister.exe.config file in the same folder as the executable, per-user settings are in %localappdata%\DirLister\ folder (created after running the program). There is also "Open DirLister configuration folder" button in the About tab

**Comment by fireattack** [comment]
Understood.
