### ISSUE TITLE
Feature request: Provide option to include directories when listing folder or drive contents

### ISSUE THREAD

**Issue by onmyouji** [SanderSade/DirLister#8]
Hello,

Currently when listing a folder contents, DirLister only show the files but not directories. Is it possible to provide an option to include directories? I mean something that looks like this:

![Image 3](https://user-images.githubusercontent.com/8424198/75604524-092e8400-5b0c-11ea-981c-bde8728013f6.png)

**Comment by SanderSade** [comment]
It is possible and not complicated at all - but that would mean directory is in the output twice, once under the parent folder, and once by itself. That might be confusing for the users, even when in HTML output, the directory "above" is hyperlinked/clickable to go to "below".

What do you think, and also, what would be the use case for this?

**Comment by onmyouji** [comment]
The reason I made the suggestion is because I prefer the list to be just like the output when we use ls or dir command. Right now when I want to look what directories there are inside a drive or folder, I have to scroll all the way.

For example if I have a parent folder called Musician and inside there are directories based on their released albums. When I want to check if I already have certain albums, I have to scroll down and check all the directory one by one.

**Comment by SanderSade** [comment]
Would #9 cover this for you, e.g. Windows Explorer-like HTML output?

**Comment by onmyouji** [comment]
Yes, that would be so useful. Thanks!
